
services:
  database:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 6303
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 6303
    depends_on:
      - database
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DB: test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6303
    depends_on:
      - database 