name: CICD
on: push: [deploy-to-ec2]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t integardtionninjas/AnotationsTesting .
      - name: Publish image to docker hub
        run: docker push integardtionninjas/AnotationsTesting:latest
  deploy:
    needs: build
    run-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull integardtionninjas/AnotationsTesting:latest
      - name: Delete old container
        run: docker rm -f springboot-annotation-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-annotation-container integardtionninjas/AnotationsTesting